sudo: required
services:
  - docker

before_install:
  - docker build -t minghaoh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true minghaoh/react-test npm test

after_success:
  - docker build -t minghaoh/multi-client ./client
  - docker build -t minghaoh/multi-nginx ./nginx
  - docker build -t minghaoh/multi-server ./server
  - docker build -t minghaoh/multi-worker ./worker
## login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

## push to docker hub

  - docker push minghaoh/multi-client
  - docker push minghaoh/multi-nginx
  - docker push minghaoh/multi-server
  - docker push minghaoh/multi-worker

 ## start aws deploy section
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-700822481323
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
